import type { Express } from "express";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import type { RouteContext } from "../app-config.js";
import {
  readRunFiles,
  readRunFile,
  writeRunFileAtomic,
  readLiveOutputTail,
} from "../run-store.js";
import {
  readSuppressed,
  addSuppression,
  removeSuppression,
  applySuppressionFilter,
  isRunFullyReviewed,
  decisionFingerprint,
} from "../suppression.js";
import { sweepStaleRunning } from "../stale-runs.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
// scripts.json lives at repo-root/lib (this module is at repo-root/server/routes).
const SCRIPTS_REGISTRY = path.join(__dirname, "..", "..", "lib", "scripts.json");

// Run IDs are generated by report.sh as `${name}-${iso-date}-${pid}`, so the
// legal character set is conservative. Reject anything outside it before the id
// reaches path.join, which otherwise would allow traversal via "../".
const RUN_ID_PATTERN = /^[A-Za-z0-9._-]+$/;

export function registerRunRoutes(app: Express, ctx: RouteContext): void {
  const { config, broadcast } = ctx;

  app.param("id", (_req, res, next, id) => {
    if (!RUN_ID_PATTERN.test(id)) {
      res.status(400).json({ error: "Invalid run id" });
      return;
    }
    next();
  });

  // GET /api/runs — list recent runs (without full output for performance)
  app.get("/api/runs", (req, res) => {
    const limit = parseInt((req.query.limit as string) || "50", 10);
    const category = req.query.category as string | undefined;

    let runs = readRunFiles(config.runsDir);
    if (category) runs = runs.filter((r) => r.category === category);

    // Drop suppressed artifacts so reviewed / archived items don't reappear on
    // subsequent agent runs. Per-record so an empty artifact list still
    // surfaces the run itself (the user may want to see the summary).
    const suppressed = readSuppressed(config.suppressedFile);
    for (const r of runs) applySuppressionFilter(r, suppressed);

    // Strip output from the list view to keep the response lean.
    const summary = runs
      .slice(0, limit)
      .map(({ output: _output, ...rest }) => rest);
    res.json(summary);
  });

  // GET /api/runs/:id — single run with full output. For running runs the live
  // tail of the .output file is stitched in so the dashboard shows progress
  // mid-flight; once the run ends, report.sh writes final output into the JSON.
  app.get("/api/runs/:id", (req, res) => {
    const runFile = path.join(config.runsDir, `${req.params.id}.json`);
    if (!fs.existsSync(runFile)) {
      res.status(404).json({ error: "Run not found" });
      return;
    }
    const record = readRunFile(config.runsDir, req.params.id);
    if (!record) {
      res.status(500).json({ error: "Failed to read run record" });
      return;
    }
    if (record.status === "running") {
      const live = readLiveOutputTail(config.runsDir, req.params.id);
      if (live !== null) record.output = live;
    }
    applySuppressionFilter(record, readSuppressed(config.suppressedFile));
    res.json(record);
  });

  // GET /api/scripts — return the known script registry
  app.get("/api/scripts", (_req, res) => {
    try {
      res.json(JSON.parse(fs.readFileSync(SCRIPTS_REGISTRY, "utf-8")));
    } catch {
      res.status(500).json({ error: "Failed to read script registry" });
    }
  });

  // DELETE /api/runs/:id — delete a run record
  app.delete("/api/runs/:id", (req, res) => {
    const runFile = path.join(config.runsDir, `${req.params.id}.json`);
    const outputFile = path.join(config.runsDir, `${req.params.id}.output`);
    if (!fs.existsSync(runFile)) {
      res.status(404).json({ error: "Run not found" });
      return;
    }
    try {
      fs.unlinkSync(runFile);
      if (fs.existsSync(outputFile)) fs.unlinkSync(outputFile);
      res.json({ deleted: true });
    } catch {
      res.status(500).json({ error: "Failed to delete run record" });
    }
  });

  // POST /api/runs/cleanup — delete old runs.
  //   - success runs older than completedDays are pruned
  //   - failed/killed runs older than failedDays are pruned
  //   - running runs are never touched
  //   - `days` is a legacy alias applied to both when specifics are absent
  app.post("/api/runs/cleanup", (req, res) => {
    const body = (req.body ?? {}) as {
      days?: number | string;
      completedDays?: number | string;
      failedDays?: number | string;
    };
    const legacyDays = body.days != null ? Number(body.days) : undefined;
    const completedDays = Number(body.completedDays ?? legacyDays ?? 7);
    const failedDays = Number(body.failedDays ?? legacyDays ?? 30);

    if (
      !Number.isFinite(completedDays) ||
      !Number.isFinite(failedDays) ||
      completedDays < 0 ||
      failedDays < 0
    ) {
      res.status(400).json({
        error: "completedDays and failedDays must be non-negative numbers",
      });
      return;
    }

    const now = Date.now() / 1000;
    const completedCutoff = now - completedDays * 86400;
    const failedCutoff = now - failedDays * 86400;

    const runs = readRunFiles(config.runsDir);
    let deletedCompleted = 0;
    let deletedFailed = 0;

    for (const run of runs) {
      if (run.status === "running") continue;
      const cutoff = run.status === "success" ? completedCutoff : failedCutoff;
      if (run.startEpoch >= cutoff) continue;

      const runFile = path.join(config.runsDir, `${run.id}.json`);
      const outputFile = path.join(config.runsDir, `${run.id}.output`);
      try {
        fs.unlinkSync(runFile);
        if (fs.existsSync(outputFile)) fs.unlinkSync(outputFile);
        if (run.status === "success") deletedCompleted++;
        else deletedFailed++;
      } catch {
        // Skip files that can't be deleted
      }
    }

    res.json({
      deleted: deletedCompleted + deletedFailed,
      deletedCompleted,
      deletedFailed,
      completedDays,
      failedDays,
    });
  });

  // POST /api/runs/sweep-stale — force a stale sweep without waiting for the
  // timer. Also runs on a timer and at server startup.
  app.post("/api/runs/sweep-stale", (_req, res) => {
    const thresholdMs = config.staleThresholdMinutes * 60 * 1000;
    const result = sweepStaleRunning(config.runsDir, thresholdMs);
    if (result.sweptIds.length > 0) broadcast();
    res.json({ thresholdMinutes: config.staleThresholdMinutes, ...result });
  });

  // --- Review state mutation ---

  app.post("/api/runs/:id/reviewed", (req, res) => {
    const record = readRunFile(config.runsDir, req.params.id);
    if (!record) {
      res.status(404).json({ error: "Run not found" });
      return;
    }
    record.reviewedAt = new Date().toISOString();
    try {
      writeRunFileAtomic(config.runsDir, req.params.id, record);
      res.json(record);
    } catch (err) {
      console.error(`[reviewed] failed to write run ${req.params.id}:`, err);
      res.status(500).json({ error: "Failed to write run record" });
    }
  });

  app.delete("/api/runs/:id/reviewed", (req, res) => {
    const record = readRunFile(config.runsDir, req.params.id);
    if (!record) {
      res.status(404).json({ error: "Run not found" });
      return;
    }
    delete record.reviewedAt;
    try {
      writeRunFileAtomic(config.runsDir, req.params.id, record);
      res.json(record);
    } catch (err) {
      console.error(`[unreviewed] failed to write run ${req.params.id}:`, err);
      res.status(500).json({ error: "Failed to write run record" });
    }
  });

  // Per-artifact reviewed state. The run is implicitly marked reviewed when
  // every still-visible artifact has a reviewedAt, so the Needs Review queue
  // clears even without the legacy run-level button.
  app.post("/api/runs/:id/artifacts/reviewed", (req, res) => {
    const targetPath =
      typeof req.body?.path === "string" ? req.body.path : null;
    if (!targetPath) {
      res.status(400).json({ error: "Missing artifact path in body" });
      return;
    }
    const record = readRunFile(config.runsDir, req.params.id);
    if (!record) {
      res.status(404).json({ error: "Run not found" });
      return;
    }
    const artifacts = record.artifacts ?? [];
    const target = artifacts.find((a) => a.path === targetPath);
    if (!target) {
      res.status(404).json({ error: "Artifact not found on run" });
      return;
    }
    target.reviewedAt = new Date().toISOString();

    // Roll the run up to reviewed when every still-visible artifact is — the
    // shared rule the read projection uses too. Suppressed-elsewhere artifacts
    // (archived / reviewed on another run) aren't shown, so they don't block.
    if (isRunFullyReviewed(record, readSuppressed(config.suppressedFile))) {
      record.reviewedAt = target.reviewedAt;
    }

    try {
      writeRunFileAtomic(config.runsDir, req.params.id, record);
      addSuppression(config.suppressedFile, target.path, {
        reason: "reviewed",
        suppressedAt: target.reviewedAt,
        viaScript: record.script,
        viaRunId: record.id,
        // Pin the decision's state at review time so the item re-surfaces if
        // JIRA/local state later drifts (see decisionFingerprint).
        fingerprint: decisionFingerprint(target.decision),
      });
      res.json({ artifact: target, run: record });
    } catch (err) {
      console.error(
        `[artifact-reviewed] failed to write run ${req.params.id}:`,
        err,
      );
      res.status(500).json({ error: "Failed to write run record" });
    }
  });

  app.delete("/api/runs/:id/artifacts/reviewed", (req, res) => {
    const targetPath =
      typeof req.body?.path === "string" ? req.body.path : null;
    if (!targetPath) {
      res.status(400).json({ error: "Missing artifact path in body" });
      return;
    }
    const record = readRunFile(config.runsDir, req.params.id);
    if (!record) {
      res.status(404).json({ error: "Run not found" });
      return;
    }
    const artifacts = record.artifacts ?? [];
    const target = artifacts.find((a) => a.path === targetPath);
    if (!target) {
      res.status(404).json({ error: "Artifact not found on run" });
      return;
    }
    delete target.reviewedAt;

    if (record.reviewedAt && artifacts.some((a) => !a.reviewedAt)) {
      delete record.reviewedAt;
    }

    try {
      writeRunFileAtomic(config.runsDir, req.params.id, record);
      // Only clear suppression if the registry entry came from a "reviewed"
      // action — un-marking reviewed shouldn't undo an "archived" suppression.
      const reg = readSuppressed(config.suppressedFile);
      if (reg[target.path]?.reason === "reviewed") {
        removeSuppression(config.suppressedFile, target.path);
      }
      res.json({ artifact: target, run: record });
    } catch (err) {
      console.error(
        `[artifact-unreviewed] failed to write run ${req.params.id}:`,
        err,
      );
      res.status(500).json({ error: "Failed to write run record" });
    }
  });
}
