import express from "express";
import cors from "cors";
import fs from "fs";
import path from "path";
import os from "os";
import { fileURLToPath } from "url";
import {
  ArtifactError,
  archiveArtifact,
  isJiraPullableField,
  loadArtifactsConfig,
  patchArtifact,
  readArtifact,
  resolveSafePath,
  setArtifactField,
  setArtifactFields,
  snoozeArtifact,
  type ArtifactsConfig,
} from "./artifacts.js";
import { createJiraClient, JiraError, type JiraClient } from "./jira.js";
import {
  jiraToLocalStatus,
  loadStatusMapping,
  type JiraStatusMapping,
} from "./jira-status-mapping.js";
import { sweepStaleRunning } from "./stale-runs.js";
import { atomicWriteJson } from "./fs-utils.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// --- Types ---

interface SuppressionEntry {
  reason: "reviewed" | "archived";
  suppressedAt: string;
  viaScript?: string;
  viaRunId?: string;
}

type SuppressionRegistry = Record<string, SuppressionEntry>;

// Structured metadata attached to an artifact by the emitting agent. Drives
// the conditional buttons in the dashboard's review panel. Optional — agents
// that don't emit decisions render with the default edit/archive buttons.
interface ArtifactDecision {
  kind:
    | "status-divergence" // JIRA + local disagree on status
    | "local-ahead-of-jira" // local is in-progress/done but JIRA is behind
    | "backlog-stale" // backlog + no sprint + no due date
    | "local-done-jira-open" // done locally but JIRA isn't closed
    | "jira-now-done"; // JIRA closed but local still open
  jiraKey: string;
  jiraStatus?: string;
  localStatus?: string;
  note?: string; // free-form context for the dashboard card
}

interface Artifact {
  type: "task-note" | "file" | "url";
  label: string;
  path: string;
  decision?: ArtifactDecision;
  reviewedAt?: string;
}

export interface RunRecord {
  id: string;
  script: string;
  category: string;
  description?: string;
  status: "running" | "success" | "failed" | "killed";
  exitCode?: number;
  startedAt: string;
  endedAt?: string;
  startEpoch: number;
  endEpoch?: number;
  duration?: number;
  pid?: number;
  host?: string;
  output?: string;
  artifacts?: Artifact[];
  reviewRequired?: boolean;
  reviewedAt?: string;
  lastProgressAt?: string;
  lastProgressMessage?: string;
}

// --- Constants ---

// Run IDs are generated by report.sh as `${name}-${iso-date}-${pid}`, so the
// legal character set is conservative. Reject anything outside it before the
// id reaches `path.join`, which otherwise would allow traversal via "../".
const RUN_ID_PATTERN = /^[A-Za-z0-9._-]+$/;
// Issue keys look like ABC-123. Constrain before they reach JIRA / URL builders.
const JIRA_KEY_PATTERN = /^[A-Z][A-Z0-9_]+-\d+$/;
// Cap live-output responses so an unbounded log can't blow up the JSON payload.
// Matches the 100KB tail truncation that report.sh applies at end-of-run.
const LIVE_OUTPUT_TAIL_BYTES = 102_400;
const STALE_RUN_SWEEP_INTERVAL_MS = 5 * 60 * 1000;
// Per-category sweep thresholds. Interactive Claude sessions are alive across
// long idle periods (meetings, reading, lunch) and shouldn't be killed by the
// 30-min cadence that catches genuinely hung scripted jobs. 8h covers a
// workday of intermittent typing; orphans still get cleaned up within one
// calendar day if Claude Code crashes without SessionEnd.
const STALE_CATEGORY_OVERRIDES_MS: Record<string, number> = {
  interactive: 8 * 60 * 60 * 1000,
};

// --- App configuration ---

export interface AppConfig {
  runsDir: string;
  suppressedFile: string;
  artifactsConfig: ArtifactsConfig;
  jira: JiraClient | null;
  statusMapping: JiraStatusMapping;
  staleThresholdMinutes: number;
}

// Build the default config from the environment. Used by the standalone server;
// tests call createApp with their own temp-dir config instead.
export function defaultConfig(): AppConfig {
  const runsDir =
    process.env.SCRIPT_RUNS_DIR ||
    path.join(os.homedir(), ".script-runs", "runs");
  const artifactsConfig = loadArtifactsConfig();
  return {
    runsDir,
    suppressedFile:
      process.env.SCRIPT_SUPPRESSED_FILE ||
      path.join(path.dirname(runsDir), ".suppressed.json"),
    artifactsConfig,
    jira: artifactsConfig.jira ? createJiraClient(artifactsConfig.jira) : null,
    statusMapping: loadStatusMapping(),
    staleThresholdMinutes: parseInt(
      process.env.STALE_RUN_THRESHOLD_MINUTES || "30",
      10,
    ),
  };
}

export interface DashboardApp {
  app: express.Express;
  broadcastUpdate: () => void;
  runStaleSweep: () => void;
}

// createApp wires every route over an injected config so the app holds no
// module-level filesystem globals — tests construct it against a temp runs dir,
// the standalone server constructs it from defaultConfig().
export function createApp(config: AppConfig): DashboardApp {
  const app = express();
  app.use(cors());
  app.use(express.json());

  // --- Suppression registry -------------------------------------------------
  // Paths in this file are filtered out of every GET so reviewed / archived
  // items don't keep reappearing in the review queue on each agent rerun.

  function readSuppressed(): SuppressionRegistry {
    if (!fs.existsSync(config.suppressedFile)) return {};
    try {
      const parsed = JSON.parse(fs.readFileSync(config.suppressedFile, "utf-8"));
      return parsed && typeof parsed === "object" ? parsed : {};
    } catch {
      return {};
    }
  }

  function addSuppression(artifactPath: string, entry: SuppressionEntry): void {
    const reg = readSuppressed();
    reg[artifactPath] = entry;
    atomicWriteJson(config.suppressedFile, reg);
  }

  function removeSuppression(artifactPath: string): void {
    const reg = readSuppressed();
    if (!(artifactPath in reg)) return;
    delete reg[artifactPath];
    atomicWriteJson(config.suppressedFile, reg);
  }

  // Single source of truth for "is this run fully reviewed?", shared by the
  // read projection (applySuppressionFilter) and the write path
  // (POST /artifacts/reviewed), which previously carried two subtly different
  // copies of the rule (one gated on reviewRequired and ran .every() on the
  // post-filter list; the other required visible.length > 0).
  //
  // A run is fully reviewed when it emitted at least one artifact and every
  // artifact still visible to the user — not suppressed on another run unless
  // reviewed here — carries a reviewedAt. An empty visible set (all artifacts
  // archived/reviewed elsewhere) counts as fully reviewed: nothing's left to
  // act on. A run that never emitted artifacts is never auto-reviewed.
  function isRunFullyReviewed(
    record: RunRecord,
    registry: SuppressionRegistry,
  ): boolean {
    if (record.reviewedAt) return false;
    const artifacts = record.artifacts ?? [];
    if (artifacts.length === 0) return false;
    const visible = artifacts.filter(
      (a) => !(a.path in registry) || !!a.reviewedAt,
    );
    return visible.every((a) => !!a.reviewedAt);
  }

  // Drop suppressed-unreviewed artifacts from a record in place (read-time
  // projection — the on-disk record is untouched). Returns the count dropped.
  //
  // Dropped = path in registry AND no reviewedAt on this run record. This keeps
  // the SOURCE run's reviewed stub visible (so the user can undo) while
  // suppressing the same path's reappearance on every NEW run that emits it.
  // Archived artifacts always lack reviewedAt, so they're stripped cleanly.
  //
  // Also projects reviewedAt when the run is fully reviewed, so a run whose
  // unreviewed artifacts were all suppressed-elsewhere still clears the Needs
  // Review queue. Decided from the ORIGINAL list (before the in-place filter)
  // so "had artifacts, all suppressed" stays distinct from "never had any".
  function applySuppressionFilter(
    record: RunRecord,
    registry: SuppressionRegistry,
  ): number {
    if (!record.artifacts || record.artifacts.length === 0) return 0;
    const before = record.artifacts.length;
    if (isRunFullyReviewed(record, registry)) {
      record.reviewedAt = new Date().toISOString();
    }
    record.artifacts = record.artifacts.filter(
      (a) => !(a.path in registry) || !!a.reviewedAt,
    );
    return before - record.artifacts.length;
  }

  // --- Run record IO --------------------------------------------------------

  function readRunFiles(): RunRecord[] {
    if (!fs.existsSync(config.runsDir)) return [];
    const files = fs
      .readdirSync(config.runsDir)
      .filter((f) => f.endsWith(".json"));
    const runs: RunRecord[] = [];
    for (const file of files) {
      try {
        const raw = fs.readFileSync(path.join(config.runsDir, file), "utf-8");
        runs.push(JSON.parse(raw) as RunRecord);
      } catch {
        // Skip malformed files
      }
    }
    // Sort by start time, newest first
    runs.sort((a, b) => (b.startEpoch || 0) - (a.startEpoch || 0));
    return runs;
  }

  function readRunFile(id: string): RunRecord | null {
    const runFile = path.join(config.runsDir, `${id}.json`);
    if (!fs.existsSync(runFile)) return null;
    try {
      return JSON.parse(fs.readFileSync(runFile, "utf-8")) as RunRecord;
    } catch {
      return null;
    }
  }

  function writeRunFileAtomic(id: string, record: RunRecord): void {
    atomicWriteJson(path.join(config.runsDir, `${id}.json`), record);
  }

  function readLiveOutputTail(id: string): string | null {
    const outputFile = path.join(config.runsDir, `${id}.output`);
    if (!fs.existsSync(outputFile)) return null;
    try {
      const stat = fs.statSync(outputFile);
      if (stat.size === 0) return "";
      const start = Math.max(0, stat.size - LIVE_OUTPUT_TAIL_BYTES);
      const fd = fs.openSync(outputFile, "r");
      try {
        const len = stat.size - start;
        const buf = Buffer.alloc(len);
        fs.readSync(fd, buf, 0, len, start);
        return buf.toString("utf-8");
      } finally {
        fs.closeSync(fd);
      }
    } catch {
      return null;
    }
  }

  // --- SSE ------------------------------------------------------------------

  const sseClients = new Set<express.Response>();

  function broadcastUpdate(): void {
    const data = JSON.stringify({ type: "update", timestamp: Date.now() });
    for (const client of sseClients) {
      try {
        client.write(`data: ${data}\n\n`);
      } catch {
        // Socket already gone but `close` hasn't fired yet — drop it so a dead
        // client can't throw out of an otherwise-completed request handler.
        sseClients.delete(client);
      }
    }
  }

  // --- Stale sweep ----------------------------------------------------------

  function runStaleSweep(): void {
    const thresholdMs = config.staleThresholdMinutes * 60 * 1000;
    const { sweptIds } = sweepStaleRunning(
      config.runsDir,
      thresholdMs,
      Date.now(),
      STALE_CATEGORY_OVERRIDES_MS,
    );
    if (sweptIds.length > 0) {
      console.log(
        `[stale-sweep] marked ${sweptIds.length} run(s) killed:`,
        sweptIds.join(", "),
      );
      broadcastUpdate();
    }
  }

  // --- Error helpers --------------------------------------------------------

  function handleArtifactError(err: unknown, res: express.Response): void {
    if (err instanceof ArtifactError) {
      res.status(err.status).json({ error: err.message });
      return;
    }
    console.error("[artifacts] internal error:", err);
    res.status(500).json({
      error: "Internal error",
      detail: err instanceof Error ? err.message : String(err),
    });
  }

  function handleJiraError(err: unknown, res: express.Response): void {
    if (err instanceof JiraError) {
      res.status(err.status).json({ error: err.message, detail: err.detail });
      return;
    }
    console.error("[jira] internal error:", err);
    res.status(500).json({
      error: "Internal error",
      detail: err instanceof Error ? err.message : String(err),
    });
  }

  function requireJira(res: express.Response): JiraClient | null {
    if (!config.jira) {
      res
        .status(503)
        .json({ error: "JIRA integration is not configured on this server." });
      return null;
    }
    return config.jira;
  }

  function validJiraKey(key: string, res: express.Response): boolean {
    if (!JIRA_KEY_PATTERN.test(key)) {
      res.status(400).json({ error: "Invalid JIRA key" });
      return false;
    }
    return true;
  }

  // --- Routes ---------------------------------------------------------------

  app.param("id", (_req, res, next, id) => {
    if (!RUN_ID_PATTERN.test(id)) {
      res.status(400).json({ error: "Invalid run id" });
      return;
    }
    next();
  });

  // GET /api/runs — list recent runs (without full output for performance)
  app.get("/api/runs", (req, res) => {
    const limit = parseInt((req.query.limit as string) || "50", 10);
    const category = req.query.category as string | undefined;

    let runs = readRunFiles();
    if (category) runs = runs.filter((r) => r.category === category);

    // Drop suppressed artifacts so reviewed / archived items don't reappear on
    // subsequent agent runs. Per-record so an empty artifact list still
    // surfaces the run itself (the user may want to see the summary).
    const suppressed = readSuppressed();
    for (const r of runs) applySuppressionFilter(r, suppressed);

    // Strip output from list view to keep the response lean.
    const summary = runs
      .slice(0, limit)
      .map(({ output: _output, ...rest }) => rest);
    res.json(summary);
  });

  // GET /api/runs/:id — single run with full output. For running runs the live
  // tail of the .output file is stitched in so the dashboard shows progress
  // mid-flight; once the run ends, report.sh writes final output into the JSON.
  app.get("/api/runs/:id", (req, res) => {
    const runFile = path.join(config.runsDir, `${req.params.id}.json`);
    if (!fs.existsSync(runFile)) {
      res.status(404).json({ error: "Run not found" });
      return;
    }
    try {
      const record = JSON.parse(fs.readFileSync(runFile, "utf-8")) as RunRecord;
      if (record.status === "running") {
        const live = readLiveOutputTail(req.params.id);
        if (live !== null) record.output = live;
      }
      applySuppressionFilter(record, readSuppressed());
      res.json(record);
    } catch {
      res.status(500).json({ error: "Failed to read run record" });
    }
  });

  // GET /api/scripts — return the known script registry
  app.get("/api/scripts", (_req, res) => {
    const registryPath = path.join(__dirname, "..", "lib", "scripts.json");
    try {
      res.json(JSON.parse(fs.readFileSync(registryPath, "utf-8")));
    } catch {
      res.status(500).json({ error: "Failed to read script registry" });
    }
  });

  // DELETE /api/runs/:id — delete a run record
  app.delete("/api/runs/:id", (req, res) => {
    const runFile = path.join(config.runsDir, `${req.params.id}.json`);
    const outputFile = path.join(config.runsDir, `${req.params.id}.output`);
    if (!fs.existsSync(runFile)) {
      res.status(404).json({ error: "Run not found" });
      return;
    }
    try {
      fs.unlinkSync(runFile);
      if (fs.existsSync(outputFile)) fs.unlinkSync(outputFile);
      res.json({ deleted: true });
    } catch {
      res.status(500).json({ error: "Failed to delete run record" });
    }
  });

  // POST /api/runs/cleanup — delete old runs.
  //   - success runs older than completedDays are pruned
  //   - failed/killed runs older than failedDays are pruned
  //   - running runs are never touched
  //   - `days` is a legacy alias applied to both when specifics are absent
  app.post("/api/runs/cleanup", (req, res) => {
    const body = (req.body ?? {}) as {
      days?: number | string;
      completedDays?: number | string;
      failedDays?: number | string;
    };
    const legacyDays = body.days != null ? Number(body.days) : undefined;
    const completedDays = Number(body.completedDays ?? legacyDays ?? 7);
    const failedDays = Number(body.failedDays ?? legacyDays ?? 30);

    if (
      !Number.isFinite(completedDays) ||
      !Number.isFinite(failedDays) ||
      completedDays < 0 ||
      failedDays < 0
    ) {
      res.status(400).json({
        error: "completedDays and failedDays must be non-negative numbers",
      });
      return;
    }

    const now = Date.now() / 1000;
    const completedCutoff = now - completedDays * 86400;
    const failedCutoff = now - failedDays * 86400;

    const runs = readRunFiles();
    let deletedCompleted = 0;
    let deletedFailed = 0;

    for (const run of runs) {
      if (run.status === "running") continue;
      const cutoff = run.status === "success" ? completedCutoff : failedCutoff;
      if (run.startEpoch >= cutoff) continue;

      const runFile = path.join(config.runsDir, `${run.id}.json`);
      const outputFile = path.join(config.runsDir, `${run.id}.output`);
      try {
        fs.unlinkSync(runFile);
        if (fs.existsSync(outputFile)) fs.unlinkSync(outputFile);
        if (run.status === "success") deletedCompleted++;
        else deletedFailed++;
      } catch {
        // Skip files that can't be deleted
      }
    }

    res.json({
      deleted: deletedCompleted + deletedFailed,
      deletedCompleted,
      deletedFailed,
      completedDays,
      failedDays,
    });
  });

  // POST /api/runs/sweep-stale — force a stale sweep without waiting for the
  // timer. Also runs on a timer and at server startup.
  app.post("/api/runs/sweep-stale", (_req, res) => {
    const thresholdMs = config.staleThresholdMinutes * 60 * 1000;
    const result = sweepStaleRunning(config.runsDir, thresholdMs);
    if (result.sweptIds.length > 0) broadcastUpdate();
    res.json({ thresholdMinutes: config.staleThresholdMinutes, ...result });
  });

  // --- Review state mutation ---

  app.post("/api/runs/:id/reviewed", (req, res) => {
    const record = readRunFile(req.params.id);
    if (!record) {
      res.status(404).json({ error: "Run not found" });
      return;
    }
    record.reviewedAt = new Date().toISOString();
    try {
      writeRunFileAtomic(req.params.id, record);
      res.json(record);
    } catch (err) {
      console.error(`[reviewed] failed to write run ${req.params.id}:`, err);
      res.status(500).json({ error: "Failed to write run record" });
    }
  });

  app.delete("/api/runs/:id/reviewed", (req, res) => {
    const record = readRunFile(req.params.id);
    if (!record) {
      res.status(404).json({ error: "Run not found" });
      return;
    }
    delete record.reviewedAt;
    try {
      writeRunFileAtomic(req.params.id, record);
      res.json(record);
    } catch (err) {
      console.error(`[unreviewed] failed to write run ${req.params.id}:`, err);
      res.status(500).json({ error: "Failed to write run record" });
    }
  });

  // Per-artifact reviewed state. The run is implicitly marked reviewed when ALL
  // its artifacts have a reviewedAt timestamp, so the Needs Review queue still
  // clears even without the legacy run-level button.
  app.post("/api/runs/:id/artifacts/reviewed", (req, res) => {
    const targetPath =
      typeof req.body?.path === "string" ? req.body.path : null;
    if (!targetPath) {
      res.status(400).json({ error: "Missing artifact path in body" });
      return;
    }
    const record = readRunFile(req.params.id);
    if (!record) {
      res.status(404).json({ error: "Run not found" });
      return;
    }
    const artifacts = record.artifacts ?? [];
    const target = artifacts.find((a) => a.path === targetPath);
    if (!target) {
      res.status(404).json({ error: "Artifact not found on run" });
      return;
    }
    target.reviewedAt = new Date().toISOString();

    // Roll the run up to reviewed when every still-visible artifact is — the
    // shared rule the read projection uses too. Suppressed-elsewhere artifacts
    // (archived / reviewed on another run) aren't shown, so they don't block.
    if (isRunFullyReviewed(record, readSuppressed())) {
      record.reviewedAt = target.reviewedAt;
    }

    try {
      writeRunFileAtomic(req.params.id, record);
      addSuppression(target.path, {
        reason: "reviewed",
        suppressedAt: target.reviewedAt,
        viaScript: record.script,
        viaRunId: record.id,
      });
      res.json({ artifact: target, run: record });
    } catch (err) {
      console.error(
        `[artifact-reviewed] failed to write run ${req.params.id}:`,
        err,
      );
      res.status(500).json({ error: "Failed to write run record" });
    }
  });

  app.delete("/api/runs/:id/artifacts/reviewed", (req, res) => {
    const targetPath =
      typeof req.body?.path === "string" ? req.body.path : null;
    if (!targetPath) {
      res.status(400).json({ error: "Missing artifact path in body" });
      return;
    }
    const record = readRunFile(req.params.id);
    if (!record) {
      res.status(404).json({ error: "Run not found" });
      return;
    }
    const artifacts = record.artifacts ?? [];
    const target = artifacts.find((a) => a.path === targetPath);
    if (!target) {
      res.status(404).json({ error: "Artifact not found on run" });
      return;
    }
    delete target.reviewedAt;

    if (record.reviewedAt && artifacts.some((a) => !a.reviewedAt)) {
      delete record.reviewedAt;
    }

    try {
      writeRunFileAtomic(req.params.id, record);
      // Only clear suppression if the registry entry came from a "reviewed"
      // action — un-marking reviewed shouldn't undo an "archived" suppression.
      const reg = readSuppressed();
      if (reg[target.path]?.reason === "reviewed") {
        removeSuppression(target.path);
      }
      res.json({ artifact: target, run: record });
    } catch (err) {
      console.error(
        `[artifact-unreviewed] failed to write run ${req.params.id}:`,
        err,
      );
      res.status(500).json({ error: "Failed to write run record" });
    }
  });

  // --- Artifact endpoints ---

  app.get("/api/artifacts", (req, res) => {
    try {
      const { absPath } = resolveSafePath(
        (req.query.path as string) ?? "",
        config.artifactsConfig,
      );
      res.json(readArtifact(absPath));
    } catch (err) {
      handleArtifactError(err, res);
    }
  });

  app.patch("/api/artifacts", (req, res) => {
    try {
      const { absPath } = resolveSafePath(
        (req.query.path as string) ?? "",
        config.artifactsConfig,
      );
      const body = (req.body ?? {}) as Record<string, unknown>;
      const updated = patchArtifact(absPath, {
        status: typeof body.status === "string" ? body.status : undefined,
        priority: typeof body.priority === "string" ? body.priority : undefined,
        appendNote:
          typeof body.appendNote === "string" ? body.appendNote : undefined,
      });
      res.json(updated);
    } catch (err) {
      handleArtifactError(err, res);
    }
  });

  app.post("/api/artifacts/archive", (req, res) => {
    try {
      const { absPath, root } = resolveSafePath(
        (req.query.path as string) ?? "",
        config.artifactsConfig,
      );
      const result = archiveArtifact(absPath, root);
      // Suppress BOTH the original and post-archive paths. Original handles
      // run records that still reference the pre-archive location; new handles
      // agents (like todo-sync Phase 1.5) that scan the archive folder and
      // would otherwise re-emit the moved file under its new path.
      const now = new Date().toISOString();
      addSuppression(result.originalPath, { reason: "archived", suppressedAt: now });
      if (result.newPath !== result.originalPath) {
        addSuppression(result.newPath, { reason: "archived", suppressedAt: now });
      }
      res.json(result);
      broadcastUpdate(); // make the artifact disappear from listening clients
    } catch (err) {
      handleArtifactError(err, res);
    }
  });

  // --- JIRA reconciliation endpoints ---

  // GET /api/jira/:key/transitions — workflow transitions valid for this issue.
  app.get("/api/jira/:key/transitions", async (req, res) => {
    const jira = requireJira(res);
    if (!jira) return;
    if (!validJiraKey(req.params.key, res)) return;
    try {
      const transitions = await jira.listTransitions(req.params.key);
      res.json({ key: req.params.key, transitions });
    } catch (err) {
      handleJiraError(err, res);
    }
  });

  // POST /api/jira/:key/transition — apply a workflow transition by id.
  app.post("/api/jira/:key/transition", async (req, res) => {
    const jira = requireJira(res);
    if (!jira) return;
    if (!validJiraKey(req.params.key, res)) return;
    const body = (req.body ?? {}) as { transitionId?: unknown };
    if (typeof body.transitionId !== "string" || body.transitionId.length === 0) {
      res.status(400).json({ error: "transitionId (string) is required" });
      return;
    }
    try {
      await jira.transitionIssue(req.params.key, body.transitionId);
      const summary = await jira.getIssue(req.params.key);
      res.json(summary);
    } catch (err) {
      handleJiraError(err, res);
    }
  });

  // POST /api/artifacts/pull-jira?path=... — fetch a field from JIRA and write
  // it into the local Task Note. `field` is constrained to an allowlist.
  app.post("/api/artifacts/pull-jira", async (req, res) => {
    const jira = requireJira(res);
    if (!jira) return;
    try {
      const { absPath } = resolveSafePath(
        (req.query.path as string) ?? "",
        config.artifactsConfig,
      );
      const body = (req.body ?? {}) as { jiraKey?: unknown; field?: unknown };
      if (typeof body.jiraKey !== "string" || !JIRA_KEY_PATTERN.test(body.jiraKey)) {
        res.status(400).json({ error: "jiraKey is required and must look like ABC-123" });
        return;
      }
      if (typeof body.field !== "string" || !isJiraPullableField(body.field)) {
        res.status(400).json({
          error:
            "field must be one of: status, jiraStatus, sprint, jiraLabels, assignee",
        });
        return;
      }
      const summary = await jira.getIssue(body.jiraKey);

      // Two write modes:
      // - `status`: the local-taxonomy field. Map JIRA → local before writing,
      //   and refresh `jiraStatus` (raw) in the same write so they stay in sync.
      // - `jiraStatus`: raw snapshot, no mapping.
      // - everything else (sprint, labels, assignee): write verbatim.
      let updated;
      let mappingWarning: string | null = null;

      if (body.field === "status") {
        const localStatus = jiraToLocalStatus(summary.status, config.statusMapping);
        if (localStatus === null) {
          updated = setArtifactField(absPath, "jiraStatus", summary.status);
          mappingWarning = `No local mapping for JIRA status "${summary.status}". Updated jiraStatus snapshot; local status field left unchanged.`;
        } else {
          updated = setArtifactFields(absPath, {
            status: localStatus,
            jiraStatus: summary.status,
          });
        }
      } else if (body.field === "jiraStatus") {
        updated = setArtifactField(absPath, "jiraStatus", summary.status);
      } else {
        let value: unknown;
        switch (body.field) {
          case "sprint":
            value = summary.sprint ?? null;
            break;
          case "jiraLabels":
            value = summary.labels;
            break;
          case "assignee":
            value = summary.assignee ?? null;
            break;
        }
        updated = setArtifactField(absPath, body.field, value);
      }
      res.json({
        jira: summary,
        artifact: updated,
        ...(mappingWarning ? { warning: mappingWarning } : {}),
      });
      broadcastUpdate();
    } catch (err) {
      if (err instanceof ArtifactError) {
        handleArtifactError(err, res);
        return;
      }
      handleJiraError(err, res);
    }
  });

  // GET /api/jira/status-mapping — canonical JIRA → local status map so the UI
  // can preview the mapped value before the user clicks.
  app.get("/api/jira/status-mapping", (_req, res) => {
    const entries: Record<string, string> = {};
    for (const [k, v] of config.statusMapping.lookup) entries[k] = v;
    res.json({ mappings: entries });
  });

  // POST /api/artifacts/snooze?path=... — add `sync-mute-until` so the next
  // todo-sync run skips this note until the date passes.
  app.post("/api/artifacts/snooze", (req, res) => {
    try {
      const { absPath } = resolveSafePath(
        (req.query.path as string) ?? "",
        config.artifactsConfig,
      );
      const body = (req.body ?? {}) as { untilDate?: unknown };
      if (typeof body.untilDate !== "string") {
        res.status(400).json({ error: "untilDate (YYYY-MM-DD) is required" });
        return;
      }
      const updated = snoozeArtifact(absPath, body.untilDate);
      res.json(updated);
      broadcastUpdate();
    } catch (err) {
      handleArtifactError(err, res);
    }
  });

  // --- Server-Sent Events for live updates ---

  app.get("/api/events", (req, res) => {
    res.writeHead(200, {
      "Content-Type": "text/event-stream",
      "Cache-Control": "no-cache",
      Connection: "keep-alive",
    });
    res.write(":\n\n"); // SSE comment to establish connection
    sseClients.add(res);
    req.on("close", () => sseClients.delete(res));
  });

  // Serve the built frontend (production). Registered after all /api routes so
  // the SPA fallback can't shadow them.
  const distDir = path.join(__dirname, "..", "dist");
  if (fs.existsSync(distDir)) {
    app.use(express.static(distDir));
    app.get(/^\/(?!api\/).*/, (_req, res) => {
      res.sendFile(path.join(distDir, "index.html"));
    });
  }

  return { app, broadcastUpdate, runStaleSweep };
}

// --- Standalone server bootstrap (skipped when imported by tests) ---

function startServer(): void {
  const config = defaultConfig();
  const { app, broadcastUpdate, runStaleSweep } = createApp(config);
  const port = parseInt(process.env.PORT || "7890", 10);

  if (!fs.existsSync(config.runsDir)) {
    fs.mkdirSync(config.runsDir, { recursive: true });
  }

  // Watch the runs directory and broadcast SSE updates on change.
  let debounceTimer: ReturnType<typeof setTimeout> | null = null;
  fs.watch(config.runsDir, (_eventType, filename) => {
    if (!filename?.endsWith(".json")) return; // ignore .output / .tmp
    // Debounce: report.sh writes a .tmp then renames, so a single logical
    // update can fire multiple events.
    if (debounceTimer) clearTimeout(debounceTimer);
    debounceTimer = setTimeout(() => {
      broadcastUpdate();
      debounceTimer = null;
    }, 300);
  });

  app.listen(port, () => {
    console.log(`Script Dashboard API running on http://localhost:${port}`);
    console.log(`Reading runs from: ${config.runsDir}`);
    console.log(`SSE endpoint: http://localhost:${port}/api/events`);
    console.log(
      `Stale-run sweep: threshold=${config.staleThresholdMinutes}min, interval=${
        STALE_RUN_SWEEP_INTERVAL_MS / 1000
      }s`,
    );
    runStaleSweep();
    setInterval(runStaleSweep, STALE_RUN_SWEEP_INTERVAL_MS);
  });
}

// Only boot when run directly (node dist/server/index.js), not when imported by
// a test that constructs createApp with its own config.
const invokedDirectly =
  process.argv[1] && path.resolve(process.argv[1]) === __filename;
if (invokedDirectly) {
  startServer();
}
